# Site settings
title: GeekZhou
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Zhou Yan's website"
baseurl: ""
url: "http://geekzhou.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
